export const NumsObj = [
    {value: "9",
     id: "nine"},
    {value: "8",
     id: "eight"},
    {value: "7",
      id: "seven"},
    {value: "6",
      id: "six"},
    {value: "5",
      id: "five"},
    {value: "4",
      id: "four"},
    {value: "3",
      id: "three"},
    {value: "2",
      id: "two"},
    {value: "1",
      id: "one"},
    {value: "0",
      id: "zero"},
    {value: '.',
      id: "decimal"}
    ];

export const OpsObj = [
  {action: "AC",
  value: "AC",
  id: "clear"},

  {action: "*",
    value: "*",
    id: "multiply"},
  {action: "/",
    value: "/",
    id: "divide"},
  {action: "+",
    value: "+",
    id: "addition"},
  {action: "-",
    value: "-",
    id: "subtract"},
  {action: "=",
    value: "=",
    id: "equals"}
];
